l_english:
 SETTING_AUTOSAVE: "Autosave interval"
 SETTING_DEBUG_SAVES: "Number of debug saves"
 SETTING_TUTORIAL: "Tutorial"
 SETTING_DISABLED_HINTS: "Disabled hints"
 SETTING_FOCUS_ON_COMBAT: "Focus on combat"
 SETTING_TOOLTIP_DELAY: "Tooltip Delay"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nSets the delay before tooltips appear."
 SETTING_TOOLTIP_UNLOCK_TIME: "Unlock Delay"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
 SETTING_TOOLTIP_LOCK_TIME: "Lock Delay"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Locked Open Delay"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
 SETTING_Sound_Effects: "All Sound Effects"
 SETTING_Sound_Effects_TOOLTIP: "#T Sound Effects Volume\n#!Sets the volume of ALL sound effects."
 SETTING_Ambience: "Ambience"
 SETTING_Ambience_TOOLTIP: "#T Ambience Volume\n#!Sets the volume of environmental ambience."
 SETTING_TOOLTIP_MODE: "Tooltip Mode"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nSets the way tooltips \"lock in,\" enabling tooltips-in-tooltips."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Mouse Tendency"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips automatically lock in place until the cursor moves away."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Action Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPress #V Middle Mouse#! to lock and unlock tooltips."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Timer Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips are locked in place if the cursor does not move for a short while. #weak (Default setting.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Misc"
 SETTINGS_CATEGORY_TOOLTIPS: "Tooltips"
 SETTINGS_CATEGORY_SFX: "Specific Sound Effects"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "General"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Map Controls"
 SETTINGS_CATEGORY_SAVE_GAMES: "Save Games"
 SETTINGS_CATEGORY_LANGUAGE: "Language"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Advanced"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portraits"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Show graphic diseases and injuries"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nSets whether graphic injuries and diseases will be visible on character portraits."
 SETTING_SHOW_NUDITY: "Show nudity"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
 NEVER: "Never"
 MONTHLY: "Every month"
 HALFYEAR: "Every 6 months"
 YEARLY: "Every year"
 FIVE_YEAR: "Every 5 years"
 SETTINGS_CATEGORY_TUTORIAL: "Tutorial"
 SETTING_REACTIVE_TUTORIAL: "Show Reactive Advice"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nSets if the game should show tutorial Advice reacting to how you play. Useful for players new to Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS: "Show Suggestions"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nSets if the game should suggest something to do at regular intervals. Useful for players new to Crusader Kings III."
 RESET_REACTIVE_ADVICE: "Reset Reactive Advice"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Reset Reactive Advice#!\nPreviously seen Reactive Advice will show up once more."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Reset Reactive Advice"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Are you sure you want to Reset Reactive Advice?"
 SETTING_ADVANCED_SHADERS: "Advanced Shader Effects"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Advanced Shader Effects\n#!This option will enable advanced shader effects.\n\nTurning it off may increase performance at the cost of making some effects (e.g. terrain and water) look worse"
 BASED_ON_ZOOM_LEVEL: "Dynamic"
 ALWAYS_HIDE: "Always Hide"
 ALWAYS_SHOW: "Always Show"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Coastal Borders"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nThis option will control when coastal realm borders should be shown.\nIf $BASED_ON_ZOOM_LEVEL$ then they will be hidden in the detail zoom level.\n\nPicking a $ALWAYS_SHOW$ or $ALWAYS_HIDE$ may increase performance at the cost of the coastal realm borders not hiding dynamically."
